export const API_ERROR_CODES = [
  "AUTH_REQUIRED",
  "AUTH_FORBIDDEN",
  "VALIDATION_ERROR",
  "PRODUCT_NOT_FOUND",
  "PRODUCT_DELETED",
  "PRODUCT_RELATED_RESOURCE_UNAVAILABLE",
  "CATEGORY_NOT_FOUND",
  "TAG_NOT_FOUND",
  "TASK_NOT_FOUND",
  "CATEGORY_IN_USE",
  "TAG_IN_USE",
  "DUPLICATE_NAME",
  "IMAGE_LIMIT_EXCEEDED",
  "UNSUPPORTED_IMAGE_TYPE",
  "IMAGE_TOO_LARGE",
  "IMAGE_NOT_FOUND",
  "INVALID_STATUS_FOR_QR_SELL",
  "ALREADY_SOLD",
  "INTERNAL_ERROR"
] as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[number];
